# Generated by Django 4.1.7 on 2023-03-25 07:04

import django.core.validators
from django.db import migrations, models
import review_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('review_app', '0002_remove_post_likes_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='/uploads/def/gray_pic.jpg', upload_to=review_app.models.upload_to),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)]),
        ),
    ]
